### ISSUE TITLE
Houston for VSCodium

### ISSUE THREAD

**Issue by djmtype** [withastro/houston-vscode#22] opened 2023-06-15 17:32 UTC
Please make this theme available to the marketplace VSCodium uses.

**Comment by CommanderGL** [comment] 2023-07-10 18:05
There is already an issue for this: https://github.com/withastro/houston-vscode/issues/12#issue-1533391830

**Comment by Princesseuh** [comment] 2023-10-25 10:40
Closing as duplicate of #12

**Closed as completed by Princesseuh** 2023-10-25 10:40 UTC
